({
 handleUrlChange : function(component, event, helper) {
        //Grab the value from the attribute or you can use event.getParam("value");
        var imageUrl = component.get("v.image");
     if(imageUrl != ""){
          var newMapAttributes = {"src": imageUrl};
        component.find("imgDiv").set("v.HTMLAttributes",newMapAttributes);
     }
        //Define the map, find the img tag generated by aura:html, 
        //and set the HTMLAttributes to your map
       
    },
    colorChanger : function(component, event, helper) {
       var myDiv = component.find("accDiv").getElement();

        // Change the background color dynamically
        myDiv.style.backgroundColor = component.get("v.BackgroundColor"); 
    },
       fontChange : function(component, event, helper) {
         //  var element = component.find("fontSizeClass").getElement();
       var element1 = component.find("fontSizeClass1").getElement();
        var element2 = component.find("fontSizeClass2").getElement();
           var element3 = component.find("fontSizeClass3").getElement();
           var element4 = component.find("fontSizeClass4").getElement();

        // Change the font size dynamically
         element1.style.fontSize = component.get("v.FontSize");
        element1.style.fontSize = component.get("v.FontSize"); // Set your desired font size
        element2.style.fontSize = component.get("v.FontSize");
               element3.style.fontSize = component.get("v.FontSize");
               element4.style.fontSize = component.get("v.FontSize");
    },
    fontcolorchange : function(component, event, helper){
      //  var element = component.find("fontSizeClass").getElement();
     helper.fontcolorchangee(component,event,helper);
        
    }
})